# This is a basic workflow to help you get started with Actions

name: "Update Module"

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-script:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update module
        run: . ./UpdateModule.ps1 -Verbose
        shell: pwsh

